### ISSUE TITLE
7800 support - jumpers for pins 5 and 9

### ISSUE THREAD

**Issue by RetroInVitro** [qoq/wiijoy#1]
Do you just mean to have a wire between 5 and 9 somewhere along the way between the DB9 connector and the MCU?

**Comment by qoq** [comment]
The board does not have traces from DB9 pins 5 and 9 to the MCU. You need to add them using jumper wires.

**Comment by RetroInVitro** [comment]
> The board does not have traces from DB9 pins 5 and 9 to the MCU. You need to add them using jumper wires.

Can you tell if the attached photos for the pins 5 and 9 are connected to the MCU properly?

I don't have an Atari 7800 but I can tell with a Wii Gamepad that pressing Select disables autofire and pressing Start on it enables it.   Is this an indicator that the current beta 7800 mode is working properly?

![Screen Shot 2023-02-04 at 12 08 03 PM](https://user-images.githubusercontent.com/32917592/216782817-4aef5388-79aa-47ef-a3b9-0f221c041d3e.jpg)
![Screen Shot 2023-02-04 at 12 08 22 PM](https://user-images.githubusercontent.com/32917592/216782818-a872a3ac-2766-464b-b7c9-0301f49ccc72.jpg)

**Comment by qoq** [comment]
Jump wires are connected properly. Start  & Select buttons on Classic controller enable/disable two-button 7800 mode. I cannot test it, unfortunately, as I don't have a 7800. Autofire is disabled in the 2-button mode. On nunchuck holding Z while powering up  enables 2-button mode.

**Comment by RetroInVitro** [comment]
Thank you for the validation.   If I understood you properly, being able to toggle autofire on or off is a good test that pins 5 and 9 are connected and that the current beta functionality is at least recognizing this new mode?
