### ISSUE TITLE
Compatibility with the ColecoVision in regular 1-button or 7800 mode 

### ISSUE THREAD

**Issue by RetroInVitro** [qoq/wiijoy#2]
So the ColecoVision can use single button Atari DB9 controllers stock for single button games.   However, the WiiJoy doesn't seem to like acting as either a regular 1-button 2600 (w/o jumpers) or 2-button 7800 controller on the ColecoVision when a regular 2600 and 7800 controller work respectively.

I recognize there is no stated support for the ColecoVision.   I'm just trying to understand the extent of 2600 and 7800 (beta as of this writing) compatibility with the adapter.   Thank you!

**Comment by qoq** [comment]
Don't have ColecoVision. Assuming that the pinout is the same, one possible reason for WiijJoy to not work is that it uses internal weak pull-ups on data lines. They might not be sufficient to drive inputs on ColecoVision. If you can add pull-up resistors between pins 1,2,3,4,6 of the DB9 connector and +5v (pin 7 on DB9), it might help. Resistors between 4.7k and 10k should work.

**Comment by RetroInVitro** [comment]
Thank you for the explanation!

**Comment by qoq** [comment]
I think the issue is that ColecoVision does not supply power (+5V) on pin7 of the DB9 connector, so WiiJoy cannot function. It works fine with Atari 2600.
